"import { useState, useEffect } from 'react';" 
"import { Animal } from '../types/animal.types';" 
"import { animalService } from '../services/animal.service';" 
"" 
"export function useAnimal(id: number) {" 
"  const [animal, setAnimal] = useState<Animal | null>(null);" 
"  const [loading, setLoading] = useState(false);" 
"  const [error, setError] = useState<string | null>(null);" 
"" 
"  useEffect(() => {" 
"    if (!id) return;" 
"" 
"    const fetchAnimal = async () => {" 
"      setLoading(true);" 
"      setError(null);" 
"      try {" 
"        const data = await animalService.getAnimalById(id);" 
"        setAnimal(data);" 
"      } catch (err: any) {" 
"        setError(err.response?.data?.message || 'Erro ao buscar animal');" 
"      } finally {" 
"        setLoading(false);" 
"      }" 
"    };" 
"" 
"    fetchAnimal();" 
"  }, [id]);" 
"" 
"  return {" 
"    animal," 
"    loading," 
"    error," 
"  };" 
"}" 
